### PR TITLE
(#8) feat: create docker container

### PR DESCRIPTION
**Pull request by ifirmawan**
I'm back here again, just adding some additional way 🕺

### CODE REVIEW

**Comment by satyawikananda** [comment]
Thanks for your PR, I have a question, is there any additional way to install this project using docker? if so, maybe we need a guideline for how to install this project using docker and put in the readme file.

**Comment by ifirmawan** [comment]
Hi @satyawikananda , Yes. We need to run docker command to run it. 
I'm working to update the readme

**Comment by satyawikananda** [comment]
Is this ready to merge?

**Comment by ifirmawan** [comment]
Yes, go ahead :)

**Comment by satyawikananda** [comment]
Thank you :)

**Comment by satyawikananda** [comment]
@all-contributors please add @ifirmawan for code, doc and ideas

**Pull request merged**
